### ISSUE TITLE
Accessors to current frame width and height

### ISSUE THREAD

**Issue by alesegdia** [kikito/anim8#13]
Like `anim:getWidth()` and `anim:getHeight()`, or maybe more explicit like `anim:getCurrentFrameWidth()`. What do you think about this?

**Comment by kikito** [comment]
Hi! Sorry it took me a while to answer this.

I have released a new version of anim8 which includes a new method, `anim:getDimensions()`. It returns *both* the width and height of the current frame in a single call, so the usage is like this:

``` lua
local w,h = anim:getDimensions()
```

Appart from this, it is very similar to your recommendation. Thanks a lot!

**Comment by alesegdia** [comment]
Nice. Thanks!
