### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by magroski** [kikito/anim8#23]
I think there's room for improvement on the Grid:getFrames(...) explanation.

Only after reading the demo code I understood how the parameters order affect the frames it fetches.

g('range', value) will fetch frames contained in the given range at row 'value'. frames are counted on the x-axis
g(value, 'range') will fetch frames contained in the given range at column 'value'.  frames are counted on the y-axis

However, it's still not clear what calls such as g('2-8',1, 1,2) will work or in what ways I can use the function

**Comment by kikito** [comment]
Hi there, thanks for opening this issue.

Do you think you could send me a PR for improving the docs? If not, could you write the text you think should be written on the docs here?

**Comment by magroski** [comment]
Sure, it'll be a pleasure.

I still want to run a couple more experiments with the lib and after that I'll send the PR. Probably over the weekend.

By the way, great work with this lib and bump

**Comment by magroski** [comment]
PR #24 created!

**Comment by kikito** [comment]
Closing by #24, thanks!
