### ISSUE TITLE
Multiple instances of anim8 causes distorted sprite

### ISSUE THREAD

**Issue by skippa** [kikito/anim8#35]
I'm using class.lua and anim8 so I can create sprite objects (say 100 coins placed across the screen). I pass the spritesheet image along with other parameters to the init function of the class, which in turn creates a grid and animation. The class also has update(dt) and render() to draw.

Strange thing is, when I create these multiple instances, one of the sprites becomes distorted. When I have only one instance, everything works as its supposed to... 

Any ideas?

**Comment by Krunklehorn** [comment]
Can you provide a code example that recreates the issue?

**Comment by skippa** [comment]
Checkout this repo https://github.com/skippa/scratch

If you swap around the init for `bluePotion` and `coins` in `main.lua`, it will distort whichever gets called first

**Comment by skippa** [comment]
you'll also notice that when each of the init calls above passes different duration parameters, both will become the lowest duration eg one is 0.5, the other is 0.1, both will refresh their frames as if duration is 0.1

**Comment by skippa** [comment]
My friend, I think you just found the issue! I'll test it out, but I'm pretty sure that's it. Yes, I meant to do self.itemAnimation, can't believe I overlooked that *facepalm* :)

**Comment by skippa** [comment]
I really should pay attention to variable definitions!

**Comment by Krunklehorn** [comment]
You really only make this mistake once. Good luck for the future!
