### ISSUE TITLE
'flipH' issue

### ISSUE THREAD

**Issue by DarkblooM-IO** [kikito/anim8#44]
When I apply `:clone():flipH()` to an animation it becomes all squished and doesn't update frames, is this normal?
![Screenshot from 2024-09-22 11-46-41](https://github.com/user-attachments/assets/5f358f41-125d-48b1-8917-97ff2e1fd481)
![Screenshot from 2024-09-22 11-46-46](https://github.com/user-attachments/assets/01a68fd9-0053-4d06-bc1c-2f42ec97c61e)

**Comment by patricknasciment** [comment]
How did you overcome this issue?

**Comment by patricknasciment** [comment]
I don't know why yet, but when you set the offset values to zero, the squished situation is corrected. Here's my example:

`   
function love.draw()
    
    player.stateAnimation:draw(player.sprintSheet, player.x, player.y, 0, 3, 3, 0, 0) <-- 
        The ofset values are the two zeros by the end
end

`

**Comment by maulrman** [comment]
@patricknasciment , when drawing the animation make sure the scale for sx and sy are the same.
